name: pyramid_lint
description: >-
  Linting tool for Dart and Flutter projects to encourage good coding practices.
version: 2.0.1
repository: https://github.com/charlescyt/pyramid_lint
issue_tracker: https://github.com/charlescyt/pyramid_lint/issues
documentation: https://docs.page/charlescyt/pyramid_lint
topics: [lint, lints, linter, analyzer]

screenshots:
  - description: >-
      Demonstration of the proper_super_init_state lint and its quick fix.
    path: screenshots/proper_super_init_state_demo.gif
  - description: >-
      Demonstration of the prefer_dedicated_media_query_method_demo lint and its quick fix.
    path: screenshots/prefer_dedicated_media_query_method_demo.gif
  - description: >-
      Demonstration of the wrap_with_layout_builder assist.
    path: screenshots/wrap_with_layout_builder_demo.gif

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  analyzer: ^6.6.0
  analyzer_plugin: ^0.11.2
  collection: ^1.17.1
  custom_lint_builder: ^0.7.0
  meta: ^1.9.1
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  yaml: ^3.1.2
