name: pyramid_lint_test
description: Test for pyramid_lint
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.5
  custom_lint: ^0.8.1
  custom_lint_core: ^0.8.1
  flutter_test:
    sdk: flutter
  path: ^1.8.3
  pub_semver: ^2.1.4
  pubspec_parse: ^1.5.0
  pyramid_lint:
    path: ../pyramid_lint
  test: ^1.26.3
